version: '3'

services:
  jeykll-serer:
    image: keithbloom/github-pages:initial
    container_name: brighton-alt-net-jekyll-server
    volumes:
      - ./:/usr/src/app
    command: jekyll serve -d /_site --watch --force_polling -H 0.0.0.0 -P 4000 
    ports:
      - 4000:4000
           