version: '3'

services:
  jeykll-serer:
    image: jekyll/jekyll
    container_name: brighton-alt-net-jekyll-server
    environment:
            - JEKYLL_ENV=docker
    volumes:
      - ./:/srv/jekyll
    command: jekyll serve --config _config.docker.yml --force_polling 
    ports:
      - 4000:4000
           