version: '3'

services:
  jeykll-serer:
    image: starefossen/github-pages
    container_name: brighton-alt-net-jekyll-server
    volumes:
      - ./:/usr/src/app
    ports:
      - 4000:4000
           